version: "3"
services:
  mongo:
    container_name: local_mongo
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  gofhir:
    container_name: gofhir
    build: ./gofhir
    command: -db.host mongo
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    links:
      - mongo

  graphql-app:
    container_name: graphql-app
    restart: always
    build: ./graphql-app
    ports:
      - "8004:8004"
    links:
      - gofhir
    depends_on:
      - gofhir